services:
  bot:
    build: .
    volumes:
      - ./queue_lessons_odd.txt:/app/queue_lessons_odd.txt
      - ./queue_lessons_even.txt:/app/queue_lessons_even.txt
      - ./check_lessons_odd.txt:/app/check_lessons_odd.txt
      - ./check_lessons_even.txt:/app/check_lessons_even.txt
      - ./.env:/app/.env:ro
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      QUEUE_CHAT_ID: ${QUEUE_CHAT_ID}
      CHECK_CHAT_ID: ${CHECK_CHAT_ID}
      NOTIFY_MINUTES_BEFORE: ${NOTIFY_MINUTES_BEFORE:-30}
    restart: unless-stopped

  poll_vote:
    build: .
    command: ["python", "poll_vote.py"]
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
